name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main and develop branches.
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format
        run: |
          black --version
          black . --check

      - name: Lint
        run: |
          make lint

      - name: Cache coverage score
        id: cache-coverage-score
        uses: actions/cache@v3
        with:
          key: coverage-score
          path: coverage-score.txt

      - name: Unit tests
        run: |
          coverage run -m pytest

      - name: End-to-end tests
        run: |
          coverage run -m test.ci

      - name: Coverage
        run: |
          # combine results of the preceding coverage runs
          coverage combine
          coverage report
          coverage report --format=total | ./check_coverage_score.py

